printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: always
endOfLine: lf
proseWrap: always

overrides:
  - files: "*.yaml"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
  - files: "*.json"
    options:
      tabWidth: 2
  - files: "*.md"
    options:
      proseWrap: preserve
