extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable   
  trailing-spaces: enable
  indentation:
    indent-sequences: true
    check-multi-line-strings: false
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false
