name: "Docker Build and Push"
description: "Build and push Docker image to registries"

inputs:
  context:
    description: "Docker build context"
    required: false
    default: "."
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: "./Dockerfile"
  tags:
    description: "Comma-separated list of tags"
    required: true
  push:
    description: "Whether to push the image"
    required: false
    default: "false"
  cache-from:
    description: "Cache from type"
    required: false
    default: "type=gha"
  cache-to:
    description: "Cache to type"
    required: false
    default: "type=gha,mode=max"
  load:
    description: "Load image instead of pushing"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push == 'true' }}
        load: ${{ inputs.load == 'true' }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
